package com.codewithrish.pdfreader.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0C0C0C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EEFFD)
val onPrimaryContainerLight = Color(0xFF001F24)
val secondaryLight = Color(0xFF4A6267)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE7EC)
val onSecondaryContainerLight = Color(0xFF051F23)
val tertiaryLight = Color(0xFF525E7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDAE2FF)
val onTertiaryContainerLight = Color(0xFF0E1B37)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFF6F5F2)
val onSurfaceVariantLight = Color(0xFF757575)
val outlineLight = Color(0xFF6F797A)
val outlineVariantLight = Color(0xFFBFC8CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF82D3E0)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryDark = Color(0xFFFAFAFA)
val onPrimaryDark = Color(0xFF00363D)
val primaryContainerDark = Color(0xFF004F58)
val onPrimaryContainerDark = Color(0xFF9EEFFD)
val secondaryDark = Color(0xFFB1CBD0)
val onSecondaryDark = Color(0xFF1C3438)
val secondaryContainerDark = Color(0xFF334B4F)
val onSecondaryContainerDark = Color(0xFFCDE7EC)
val tertiaryDark = Color(0xFFBAC6EA)
val onTertiaryDark = Color(0xFF24304D)
val tertiaryContainerDark = Color(0xFF3B4664)
val onTertiaryContainerDark = Color(0xFFDAE2FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0C0C0C)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF0C0C0C)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF1C1C1C)
val onSurfaceVariantDark = Color(0xFFEAEAEA)
val outlineDark = Color(0xFF899294)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF006874)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)

val pdfRedColor = Color(0xFFC91E1E)
val greenTick = Color(0xFF63A965)

@Composable
fun materialColor() = MaterialTheme.colorScheme


